service: handyman-sls-testx


provider:
  name: aws
  runtime: nodejs16.x

plugins:
  #  - TODO hotreload not working
  - serverless-plugin-typescript
  - serverless-offline

functions:
  DecoratedHandler:
    handler: src/functions/DecoratedHandler.handler
    events:
      - http:
          path: /decoratedHandler/{farmId}/{deviceId}/{deviceType}
          method: post
