service: handyman-sls-testx

provider:
  name: aws
  runtime: nodejs16.x

plugins:
  #  - TODO hotreload not working
  - serverless-esbuild
#  - serverless-plugin-typescript
  - serverless-offline

functions:
  DecoratedHandler:
    handler: src/functions/DecoratedHandler.handler
    events:
      - http:
          path: /decoratedHandler/{farmId}/{deviceId}/{deviceType}
          method: post
  Hello:
    handler: src/functions/Hello.handler
    events:
      - http:
          path: /hello/{name}
          method: post

custom:
  esbuild:
    config: './esbuild.config.ts'
